AWSTemplateFormatVersion: '2010-09-09'
Description: >
  Shib role for specifically tagged resource access.
Parameters:
  TagKey:
    Description: Tag key to match between IAM role and resources (ie. eds:team)
    Type: String
  TagValue:
    Description: Tag value name (ie. analytics)
    Type: String
  S3Access:
    Description: Access to S3 Resources?
    Default: 'no'
    Type: String
    AllowedValues: ['yes', 'no']
  EC2Access:
    Description: Access to EC2 Resources?
    Default: 'no'
    Type: String
    AllowedValues: ['yes', 'no']
  DMSAccess:
    Description: Access to DMS Resources?
    Default: 'no'
    Type: String
    AllowedValues: ['yes', 'no']
  SQSAccess:
    Description: Access to SQS Resources?
    Default: 'no'
    Type: String
    AllowedValues: ['yes', 'no']
  ECSAccess:
    Description: Access to ECS Resources?
    Default: 'no'
    Type: String
    AllowedValues: ['yes', 'no']
  GlueAccess:
    Description: Access to Glue Resources?
    Default: 'no'
    Type: String
    AllowedValues: ['yes', 'no']
  BucketName:
    Description: S3 bucket name to grant access to (if applicable)
    Type: String

Conditions:
  CreateS3: !Equals [ !Ref S3Access, 'yes' ]
  CreateEC2: !Equals [ !Ref EC2Access, 'yes' ]
  CreateDMS: !Equals [ !Ref DMSAccess, 'yes' ]
  CreateSQS: !Equals [ !Ref SQSAccess, 'yes' ]
  CreateECS: !Equals [ !Ref ECSAccess, 'yes' ]
  CreateGlue: !Equals [ !Ref GlueAccess, 'yes' ]

Resources:
  TagBasedResourceGroup:
    Type: AWS::ResourceGroups::Group
    Properties:
      Name: !Join [ '-', [ 'tagged', !Ref TagValue ] ]
      Description: !Sub "A group that is based on a tag query - ${TagValue}"
      ResourceQuery:
        Type:
          "TAG_FILTERS_1_0" 
        Query:
          ResourceTypeFilters: 
            - "AWS::AllSupported" 
          TagFilters:
            - 
              Key: !Ref TagKey
              Values: 
                - !Ref TagValue

  IAMRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Join [ '-', [ 'shib', !Ref TagValue ] ]
      Tags:
        - Key: !Ref TagKey
          Value: !Ref TagValue
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          -
            Effect: Allow
            Principal:
              Federated: !Sub "arn:${AWS::Partition}:iam::${AWS::AccountId}:saml-provider/cornell_idp"
            Action: sts:AssumeRoleWithSAML
            Condition:
              StringEquals:
                SAML:aud: https://signin.aws.amazon.com/saml
                
  ResourceGroupPolicy:
    DependsOn: TagBasedResourceGroup
    Type: 'AWS::IAM::Policy'
    Properties:
      PolicyName: !Join [ '-', [ 'resource', 'groups', !Ref TagValue ] ]
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          -
            Effect: Allow
            Action: 
              - 'tag:*'
              - 'resource-groups:ListGroups'
            Resource: '*'
          - 
            Effect: Allow
            Action: 
              - 'resource-groups:List*'
              - 'resource-groups:Get*'
              - 'resource-groups:SearchResources'
            Resource: !GetAtt TagBasedResourceGroup.Arn
      Roles:
        - !Ref IAMRole

  S3Policy:
    Condition: CreateS3
    Type: 'AWS::IAM::Policy'
    Properties:
      PolicyName: !Join [ '-', [ 's3', !Ref TagValue ] ]
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          -
            Effect: Allow
            Action: 's3:*'
            Resource:
              - !Sub 'arn:${AWS::Partition}:s3:::${BucketName}'
              - !Sub 'arn:${AWS::Partition}:s3:::${BucketName}/*'
          -
            Effect: Allow
            Action: 's3:ListAllMyBuckets'
            Resource: '*'
          - 
            Effect: Deny
            Action: 's3:PutBucketTagging'
            Resource: '*'
      Roles:
        - !Ref IAMRole

  EC2Policy:
    Condition: CreateEC2
    Type: 'AWS::IAM::Policy'
    Properties:
      PolicyName: !Join [ '-', [ 'ec2', !Ref TagValue ] ]
      PolicyDocument:
        !Sub 
          - |
            {
                "Version": "2012-10-17",
                "Statement": [
                    {
                        "Effect": "Allow",
                        "Action": [
                            "ec2:DescribeInstances"
                        ],
                        "Resource": "*"
                    },
                    {
                        "Effect": "Allow",
                        "Action": [
                            "ec2:StartInstances",
                            "ec2:StopInstances"
                        ],
                        "Resource": "*",
                        "Condition": {
                            "StringEquals": {
                                "${key}": "${value}"
                            }
                        }
                    },
                    {
                        "Effect": "Deny",
                        "Action": [
                            "ec2:CreateTags",
                            "ec2:DeleteTags"
                        ],
                        "Resource": "*"
                    }
                ]
            }
          -
            key: !Sub 'aws:ResourceTag/${TagKey}'
            value: !Join [ '', [ !Join [ '/', [ '${aws:PrincipalTag', !Ref TagKey ] ], '}' ] ]
      Roles:
        - !Ref IAMRole

  DMSPolicy:
    Condition: CreateDMS
    Type: 'AWS::IAM::Policy'
    Properties:
      PolicyName: !Join [ '-', [ 'dms', !Ref TagValue ] ]
      PolicyDocument:
        !Sub 
          - |
            {
                "Version": "2012-10-17",
                "Statement": [
                    {
                        "Action": [
                            "dms:Describe*"
                        ],
                        "Resource": "*",
                        "Effect": "Allow"
                    },
                    {
                        "Action": [
                            "dms:RemoveTagsFromResource",
                            "dms:AddTagsToResource"
                        ],
                        "Resource": "*",
                        "Effect": "Deny"
                    },
                    {
                        "Action": [
                            "dms:TestConnection",
                            "dms:ListTagsForResource",
                            "dms:DescribeReplicationTaskIndividualAssessments",
                            "dms:StartReplicationTask",
                            "dms:StartReplicationTaskAssessmentRun",
                            "dms:DescribeApplicableIndividualAssessments",
                            "dms:DescribeReplicationTaskAssessmentRuns",
                            "dms:StopReplicationTask",
                            "dms:DescribeReplicationInstanceTaskLogs",
                            "dms:DescribeTableStatistics",
                            "dms:StartReplicationTaskAssessment",
                            "dms:DescribeReplicationTaskAssessmentResults"
                        ],
                        "Resource": [
                            "arn:aws:dms:*:${account}:rep:*",
                            "arn:aws:dms:*:${account}:task:*",
                            "arn:aws:dms:*:${account}:endpoint:*"
                        ],
                        "Condition": {
                            "StringEquals": {
                                "${key}": "${value}"
                            }
                        },
                        "Effect": "Allow"
                    },
                    {
                        "Action": [
                            "kms:ListAliases",
                            "kms:DescribeKey"
                        ],
                        "Resource": "*",
                        "Effect": "Allow"
                    },
                    {
                        "Action": [
                            "iam:GetRole"
                        ],
                        "Resource": "*",
                        "Effect": "Allow"
                    },
                    {
                        "Action": [
                            "ec2:DescribeVpcs",
                            "ec2:DescribeInternetGateways",
                            "ec2:DescribeAvailabilityZones",
                            "ec2:DescribeSubnets",
                            "ec2:DescribeSecurityGroups"
                        ],
                        "Resource": "*",
                        "Effect": "Allow"
                    },
                    {
                        "Action": [
                            "cloudwatch:Get*",
                            "cloudwatch:List*"
                        ],
                        "Resource": "*",
                        "Effect": "Allow"
                    }
                ]
            }
          -
            key: !Sub 'aws:ResourceTag/${TagKey}'
            value: !Join [ '', [ !Join [ '/', [ '${aws:PrincipalTag', !Ref TagKey ] ], '}' ] ]
            account: !Ref 'AWS::AccountId'
      Roles:
        - !Ref IAMRole

  SQSPolicy:
    Condition: CreateSQS
    Type: 'AWS::IAM::Policy'
    Properties:
      PolicyName: !Join [ '-', [ 'sqs', !Ref TagValue ] ]
      PolicyDocument:
        !Sub 
          - |
            {
                "Version": "2012-10-17",
                "Statement": [
                    {
                        "Effect": "Allow",
                        "Action": [
                            "sqs:*"
                        ],
                        "Resource": "*"
                    }
                ]
            }
          -
            key: !Sub 'aws:ResourceTag/${TagKey}'
            value: !Join [ '', [ !Join [ '/', [ '${aws:PrincipalTag', !Ref TagKey ] ], '}' ] ]
      Roles:
        - !Ref IAMRole

  ECSPolicy:
    Condition: CreateECS
    Type: 'AWS::IAM::Policy'
    Properties:
      PolicyName: !Join [ '-', [ 'ecs', !Ref TagValue ] ]
      PolicyDocument:
        !Sub 
          - |
            {
                "Version": "2012-10-17",
                "Statement": [
                    {
                        "Effect": "Allow",
                        "Action": [
                            "ecs:List*"
                        ],
                        "Resource": "*"
                    },
                    {
                        "Effect": "Allow",
                        "Action": [
                            "ecs:*"
                        ],
                        "Resource": "*",
                        "Condition": {
                            "StringEquals": {
                                "${key}": "${value}"
                            }
                        }
                    },
                    {
                        "Effect": "Allow",
                        "Action": [
                            "cloudwatch:GetMetricStatistics"
                        ],
                        "Resource": "*"
                    },
                    {
                        "Effect": "Deny",
                        "Action": [
                            "ecs:TagResource",
                            "ecs:UntagResource"
                        ],
                        "Resource": "*"
                    }
                ]
            }
          -
            key: !Sub 'aws:ResourceTag/${TagKey}'
            value: !Join [ '', [ !Join [ '/', [ '${aws:PrincipalTag', !Ref TagKey ] ], '}' ] ]
      Roles:
        - !Ref IAMRole

  GluePolicy:
    Condition: CreateGlue
    Type: 'AWS::IAM::Policy'
    Properties:
      PolicyName: !Join [ '-', [ 'glue', !Ref TagValue ] ]
      PolicyDocument:
        !Sub 
          - |
            {
                "Version": "2012-10-17",
                "Statement": [
                    {
                        "Effect": "Allow",
                        "Action": [
                            "glue:*"
                        ],
                        "Resource": "*"
                    },
                    {
                        "Effect": "Allow",
                        "Action": [
                            "glue:CreateConnection", 
                            "glue:UpdateConnection", 
                            "glue:GetConnection",
                            "glue:DeleteConnection"
                        ],
                        "Resource": "*",
                        "Condition": {
                            "StringEquals": {
                                "${key}": "${value}"
                            }
                        }
                    },
                    {
                        "Effect": "Deny",
                        "Action": [
                            "glue:TagResource",
                            "glue:UntagResource"
                        ],
                        "Resource": "*"
                    }
                ]
            }
          -
            key: !Sub 'aws:ResourceTag/${TagKey}'
            value: !Join [ '', [ !Join [ '/', [ '${aws:PrincipalTag', !Ref TagKey ] ], '}' ] ]
      Roles:
        - !Ref IAMRole