---
AWSTemplateFormatVersion: '2010-09-09'
Description: "Create a standard baseline Network ACL. Source: https://github.com/CU-CommunityApps/cu-aws-cloudformation/tree/master/baseline-nacl"
###############################################################################
# Change Log
# v2.0:
#   - Add rules to allow egress to LDAP servers outside of
#     Cornell campus IP space.
#   - Reduce rule count for Kerberos by allowing all types of 
#     traffic to/from Kerberos servers.
###############################################################################

Parameters:
  TargetVPCParam:
    Type: AWS::EC2::VPC::Id
    # Default:
    Description: In which VPC should this Network ACL be created?

  NACLNameParam:
    Type: String
    Default: cornell-baseline-nacl
    Description: What name do you want to use for the NACL?

Resources:

  VPCNetworkACL:
    Type: AWS::EC2::NetworkAcl
    DeletionPolicy: Retain
    Properties:
      Tags:
        - Key: Name
          Value: !Ref NACLNameParam
        - Key: Version
          Value: "2.0"
      VpcId: !Ref TargetVPCParam

  NetworkACLRuleIn0100:
    Type: AWS::EC2::NetworkAclEntry
    DeletionPolicy: Retain
    Properties:
      CidrBlock: 0.0.0.0/0
      NetworkAclId: !Ref VPCNetworkACL
      PortRange:
        From: 22
        To: 22
      Protocol: 6
      RuleAction : allow
      RuleNumber : 100

  NetworkACLRuleIn0200:
    Type: AWS::EC2::NetworkAclEntry
    DeletionPolicy: Retain
    Properties:
      CidrBlock: 0.0.0.0/0
      NetworkAclId: !Ref VPCNetworkACL
      PortRange:
        From: 80
        To: 80
      Protocol: 6
      RuleAction : allow
      RuleNumber : 200

  NetworkACLRuleIn0300:
    Type: AWS::EC2::NetworkAclEntry
    DeletionPolicy: Retain
    Properties:
      CidrBlock: 0.0.0.0/0
      NetworkAclId: !Ref VPCNetworkACL
      PortRange:
        From: 443
        To: 443
      Protocol: 6
      RuleAction : allow
      RuleNumber : 300

  NetworkACLRuleIn0400:
    Type: AWS::EC2::NetworkAclEntry
    DeletionPolicy: Retain
    Properties:
      CidrBlock: 0.0.0.0/0
      NetworkAclId: !Ref VPCNetworkACL
      PortRange:
        From: 1024
        To: 65535
      Protocol: 6
      RuleAction : allow
      RuleNumber : 400

  NetworkACLRuleIn0500:
    Type: AWS::EC2::NetworkAclEntry
    DeletionPolicy: Retain
    Properties:
      CidrBlock: 0.0.0.0/0
      NetworkAclId: !Ref VPCNetworkACL
      PortRange:
        From: 1024
        To: 65535
      Protocol: 17
      RuleAction : allow
      RuleNumber : 500

  NetworkACLRuleIn0600:
    Type: AWS::EC2::NetworkAclEntry
    DeletionPolicy: Retain
    Properties:
      CidrBlock: 0.0.0.0/0
      NetworkAclId: !Ref VPCNetworkACL
      PortRange:
        From: 123
        To: 123
      Protocol: 17
      RuleAction : allow
      RuleNumber : 600

  # Elastic IP of AWS-based Cornell Kerberos Server
  # kerberos-aws.login.cornell.edu
  NetworkACLRuleIn0610:
    Type: AWS::EC2::NetworkAclEntry
    DeletionPolicy: Retain
    Properties:
      CidrBlock: 52.200.35.38/32
      NetworkAclId: !Ref VPCNetworkACL
      Protocol: -1
      RuleAction : allow
      RuleNumber : 610

  # Elastic IP of AWS-based Cornell Kerberos Server
  # kerberos-aws2.login.cornell.edu
  NetworkACLRuleIn0620:
    Type: AWS::EC2::NetworkAclEntry
    DeletionPolicy: Retain
    Properties:
      CidrBlock: 52.201.66.104/32
      NetworkAclId: !Ref VPCNetworkACL
      Protocol: -1
      RuleAction : allow
      RuleNumber : 620

  NetworkACLRuleIn0700:
    Type: AWS::EC2::NetworkAclEntry
    DeletionPolicy: Retain
    Properties:
      CidrBlock: 10.0.0.0/8
      NetworkAclId: !Ref VPCNetworkACL
      Protocol: -1
      RuleAction : allow
      RuleNumber : 700

  NetworkACLRuleIn0800:
    Type: AWS::EC2::NetworkAclEntry
    DeletionPolicy: Retain
    Properties:
      CidrBlock: 128.84.0.0/16
      NetworkAclId: !Ref VPCNetworkACL
      Protocol: -1
      RuleAction : allow
      RuleNumber : 800

  NetworkACLRuleIn0900:
    Type: AWS::EC2::NetworkAclEntry
    DeletionPolicy: Retain
    Properties:
      CidrBlock: 128.253.0.0/16
      NetworkAclId: !Ref VPCNetworkACL
      Protocol: -1
      RuleAction : allow
      RuleNumber : 900

  NetworkACLRuleIn1000:
    Type: AWS::EC2::NetworkAclEntry
    DeletionPolicy: Retain
    Properties:
      CidrBlock: 132.236.0.0/16
      NetworkAclId: !Ref VPCNetworkACL
      Protocol: -1
      RuleAction : allow
      RuleNumber : 1000

  NetworkACLRuleIn1100:
    Type: AWS::EC2::NetworkAclEntry
    DeletionPolicy: Retain
    Properties:
      CidrBlock: 192.35.82.0/24
      NetworkAclId: !Ref VPCNetworkACL
      Protocol: -1
      RuleAction : allow
      RuleNumber : 1100

  NetworkACLRuleIn1200:
    Type: AWS::EC2::NetworkAclEntry
    DeletionPolicy: Retain
    Properties:
      CidrBlock: 192.122.235.0/24
      NetworkAclId: !Ref VPCNetworkACL
      Protocol: -1
      RuleAction : allow
      RuleNumber : 1200

  NetworkACLRuleIn1300:
    Type: AWS::EC2::NetworkAclEntry
    DeletionPolicy: Retain
    Properties:
      CidrBlock: 192.122.236.0/24
      NetworkAclId: !Ref VPCNetworkACL
      Protocol: -1
      RuleAction : allow
      RuleNumber : 1300

  NetworkACLRuleOut0100:
    Type: AWS::EC2::NetworkAclEntry
    DeletionPolicy: Retain
    Properties:
      Egress: true
      CidrBlock: 0.0.0.0/0
      NetworkAclId: !Ref VPCNetworkACL
      PortRange:
        From: 22
        To: 22
      Protocol: 6
      RuleAction : allow
      RuleNumber : 100

  NetworkACLRuleOut0200:
    Type: AWS::EC2::NetworkAclEntry
    DeletionPolicy: Retain
    Properties:
      Egress: true
      CidrBlock: 0.0.0.0/0
      NetworkAclId: !Ref VPCNetworkACL
      PortRange:
        From: 80
        To: 80
      Protocol: 6
      RuleAction : allow
      RuleNumber : 200

  NetworkACLRuleOut0300:
    Type: AWS::EC2::NetworkAclEntry
    DeletionPolicy: Retain
    Properties:
      Egress: true
      CidrBlock: 0.0.0.0/0
      NetworkAclId: !Ref VPCNetworkACL
      PortRange:
        From: 443
        To: 443
      Protocol: 6
      RuleAction : allow
      RuleNumber : 300

  NetworkACLRuleOut0400:
    Type: AWS::EC2::NetworkAclEntry
    DeletionPolicy: Retain
    Properties:
      Egress: true
      CidrBlock: 0.0.0.0/0
      NetworkAclId: !Ref VPCNetworkACL
      PortRange:
        From: 1024
        To: 65535
      Protocol: 6
      RuleAction : allow
      RuleNumber : 400

  NetworkACLRuleOut0500:
    Type: AWS::EC2::NetworkAclEntry
    DeletionPolicy: Retain
    Properties:
      Egress: true
      CidrBlock: 0.0.0.0/0
      NetworkAclId: !Ref VPCNetworkACL
      PortRange:
        From: 1024
        To: 65535
      Protocol: 17
      RuleAction : allow
      RuleNumber : 500

  NetworkACLRuleOut0600:
    Type: AWS::EC2::NetworkAclEntry
    DeletionPolicy: Retain
    Properties:
      Egress: true
      CidrBlock: 0.0.0.0/0
      NetworkAclId: !Ref VPCNetworkACL
      PortRange:
        From: 123
        To: 123
      Protocol: 17
      RuleAction : allow
      RuleNumber : 600

  # Elastic IP of AWS-based Cornell Kerberos Server
  # kerberos-aws.login.cornell.edu
  NetworkACLRuleOut0610:
    Type: AWS::EC2::NetworkAclEntry
    DeletionPolicy: Retain
    Properties:
      Egress: true
      CidrBlock: 52.200.35.38/32
      NetworkAclId: !Ref VPCNetworkACL
      Protocol: -1
      RuleAction : allow
      RuleNumber : 610

  # Elastic IP of AWS-based Cornell Kerberos Server
  # kerberos-aws2.login.cornell.edu
  NetworkACLRuleOut0620:
    Type: AWS::EC2::NetworkAclEntry
    DeletionPolicy: Retain
    Properties:
      Egress: true
      CidrBlock: 52.201.66.104/32
      NetworkAclId: !Ref VPCNetworkACL
      Protocol: -1
      RuleAction : allow
      RuleNumber : 620

  NetworkACLRuleOut0700:
    Type: AWS::EC2::NetworkAclEntry
    DeletionPolicy: Retain
    Properties:
      Egress: true
      CidrBlock: 10.0.0.0/8
      NetworkAclId: !Ref VPCNetworkACL
      Protocol: -1
      RuleAction : allow
      RuleNumber : 700

  NetworkACLRuleOut0800:
    Type: AWS::EC2::NetworkAclEntry
    DeletionPolicy: Retain
    Properties:
      Egress: true
      CidrBlock: 128.84.0.0/16
      NetworkAclId: !Ref VPCNetworkACL
      Protocol: -1
      RuleAction : allow
      RuleNumber : 800

  NetworkACLRuleOut0900:
    Type: AWS::EC2::NetworkAclEntry
    DeletionPolicy: Retain
    Properties:
      Egress: true
      CidrBlock: 128.253.0.0/16
      NetworkAclId: !Ref VPCNetworkACL
      Protocol: -1
      RuleAction : allow
      RuleNumber : 900

  NetworkACLRuleOut1000:
    Type: AWS::EC2::NetworkAclEntry
    DeletionPolicy: Retain
    Properties:
      Egress: true
      CidrBlock: 132.236.0.0/16
      NetworkAclId: !Ref VPCNetworkACL
      Protocol: -1
      RuleAction : allow
      RuleNumber : 1000

  NetworkACLRuleOut1100:
    Type: AWS::EC2::NetworkAclEntry
    DeletionPolicy: Retain
    Properties:
      Egress: true
      CidrBlock: 192.35.82.0/24
      NetworkAclId: !Ref VPCNetworkACL
      Protocol: -1
      RuleAction : allow
      RuleNumber : 1100

  NetworkACLRuleOut1200:
    Type: AWS::EC2::NetworkAclEntry
    DeletionPolicy: Retain
    Properties:
      Egress: true
      CidrBlock: 192.122.235.0/24
      NetworkAclId: !Ref VPCNetworkACL
      Protocol: -1
      RuleAction : allow
      RuleNumber : 1200

  NetworkACLRuleOut1300:
    Type: AWS::EC2::NetworkAclEntry
    DeletionPolicy: Retain
    Properties:
      Egress: true
      CidrBlock: 192.122.236.0/24
      NetworkAclId: !Ref VPCNetworkACL
      Protocol: -1
      RuleAction : allow
      RuleNumber : 1300

  # Elastic IP of AWS-based TEST directory (test.directory.cornell.edu)
  # IP address #1
  # All protocols/ports are allowed since this IP may eventually be used 
  # for other services.
  NetworkACLRuleOut1400:
    Type: AWS::EC2::NetworkAclEntry
    DeletionPolicy: Retain
    Properties:
      Egress: true
      CidrBlock: 35.170.14.255/32
      NetworkAclId: !Ref VPCNetworkACL
      Protocol: -1
      RuleAction : allow
      RuleNumber : 1400

  # Elastic IP of AWS-based TEST directory (test.directory.cornell.edu)
  # IP address #2
  # All protocols/ports are allowed since this IP may eventually be used 
  # for other services.
  NetworkACLRuleOut1500:
    Type: AWS::EC2::NetworkAclEntry
    DeletionPolicy: Retain
    Properties:
      Egress: true
      CidrBlock: 3.229.3.150/32
      NetworkAclId: !Ref VPCNetworkACL
      Protocol: -1
      RuleAction : allow
      RuleNumber : 1500

  # Elastic IP of AWS-based PROD directory (query.directory.cornell.edu)
  # IP address #1
  # All protocols/ports are allowed since this IP may eventually be used 
  # for other services.
  NetworkACLRuleOut1600:
    Type: AWS::EC2::NetworkAclEntry
    DeletionPolicy: Retain
    Properties:
      Egress: true
      CidrBlock: 3.228.209.25/32
      NetworkAclId: !Ref VPCNetworkACL
      Protocol: -1
      RuleAction : allow
      RuleNumber : 1600

  # Elastic IP of AWS-based PROD directory (query.directory.cornell.edu)
  # IP address #2
  # All protocols/ports are allowed since this IP may eventually be used 
  # for other services.
  NetworkACLRuleOut1700:
    Type: AWS::EC2::NetworkAclEntry
    DeletionPolicy: Retain
    Properties:
      Egress: true
      CidrBlock: 3.218.140.210/32
      NetworkAclId: !Ref VPCNetworkACL
      Protocol: -1
      RuleAction : allow
      RuleNumber : 1700
