---
AWSTemplateFormatVersion: '2010-09-09'

Description: Resources to relay SNS messages to a Microsoft Teams webhook.

Metadata:
  Source: https://github.com/CU-CommunityApps/cu-aws-cloudformation/sns-teams-relay/template.yaml
  Version: "3.0.0"
  RecommendedStackName: sns-teams-relay-$ENV
  ChangeLog:
    "3.0.0":
      - Breaking changes! Handle just a single SNS topic for each parameter, instead of a list.
      - replace `AlarmSNSTopicsNormal` parameter with `AlarmSNSTopicNormal`
      - replace `AlarmSNSTopicsAlert` parameter with `AlarmSNSTopicAlert`
      - add `GenericSNSTopicNormal` parameter
      - add `GenericSNSTopicAlert` parameter
      - add `AWS::SNS::Subscription` resources for each of the SNS topics in the parameters
      - add `AWS::Lambda::Permission` resources for each of the SNS topics in the parameters
    "2.1.1":
      - add support for handling CloudWatch alarms messages
      - add `AlarmSNSTopicsNormal` parameter
      - add `AlarmSNSTopicsAlert` parameter
      - add `StrftimeFormatParam` parameter
      - jumping to v2.1.1. instead of v2.1.0 to match corresponding version in https://github.com/CU-CommunityApps/tf-module-sns-teams-relay
    "2.0.0":
      - Add support for two different webhook URLs: WEBHOOK_URL_NORMAL, WEBHOOK_URL_ALERT
    "1.0.0":
      - inital release

Parameters:

  VersionParam:
    Description: CIT template version
    Type: String
    
  ContactEmailParam:
    Description: CIT contact email tag value version
    Default: cloud-support@cornell.edu
    Type: String
    
  SourceURLParam:
    Description: URL of this template in source code repository
    Default: https://github.com/CU-CommunityApps/cu-aws-cloudformation/sns-teams-relay/template.yaml
    Type: String

  EnvironmentParam:
    Description: Environment for the resources this template creates.
    Default: dev
    Type: String
    AllowedValues:
      - dev
      - test
      - prod
  
  DocumentationURLParam:
    Description: URL of documentation about this deployment or these resources
    Default: https://confluence.cornell.edu/documentation/of/this/deployment
    Type: String

  TeamsWebhookNormalURLParam:
    Description: URL for your Teams webhook for success, warning, info messages
    Type: String

  TeamsWebhookAlertURLParam:
    Description: URL for your Teams webhook for failure of any type
    Type: String

  StrftimeFormatParam:
    Description: Python strftime format string to use to convert to readable timestamps.
    Type: String
    Default: "%Y-%m-%d %H:%M UTC"

  AlarmSNSTopicNormal:
    Description: All alarm notifications coming from this SNS topic will be sent to the normal webhook.
    Default: ""
    Type: String

  AlarmSNSTopicAlert:
    Description: All alarm notifications coming from this SNS topic will be sent to the alert webhook.
    Default: ""
    Type: String

  GenericSNSTopicNormal:
    Description: All unclassified notifications coming from this SNS topic will be sent to the normal webhook.
    Default: ""
    Type: String

  GenericSNSTopicAlert:
    Description: All unclassified notifications coming from this SNS topic will be sent to the alert webhook.
    Default: ""
    Type: String

Mappings: {}

Conditions:

  AlarmSNSTopicNormalCondition: !Not [ !Equals [ !Ref AlarmSNSTopicNormal, "" ]]

  AlarmSNSTopicAlertCondition: !Not [ !Equals [ !Ref AlarmSNSTopicAlert, "" ]]

  GenericSNSTopicNormalCondition: !Not [ !Equals [ !Ref GenericSNSTopicNormal, "" ]]

  GenericSNSTopicAlertCondition: !Not [ !Equals [ !Ref GenericSNSTopicAlert, "" ]]

Resources:

  SNStoTeamsRelay:
    Type: AWS::Lambda::Function
    Properties:
      Code: lambda/
      # CodeSigningConfigArn: String
      # DeadLetterConfig: 
      #   DeadLetterConfig
      Description: Relay incoming SNS messages to a Microsoft Teams webhook
      Environment: 
        Variables:
          WEBHOOK_URL_NORMAL: !Ref TeamsWebhookNormalURLParam
          WEBHOOK_URL_ALERT: !Ref TeamsWebhookAlertURLParam
          ALARM_SNS_TOPICS_NORMAL: !Ref AlarmSNSTopicNormal
          ALARM_SNS_TOPICS_ALERT: !Ref AlarmSNSTopicAlert
          STRFTIME_FORMAT: !Ref StrftimeFormatParam
          GENERIC_SNS_TOPICS_NORMAL: !Ref GenericSNSTopicNormal
          GENERIC_SNS_TOPICS_ALERT: !Ref GenericSNSTopicAlert
      # FileSystemConfigs: 
      #   - FileSystemConfig
      FunctionName: !Sub "sns-teams-relay-${EnvironmentParam}"
      Handler: sns-teams-relay.handler
      # ImageConfig: 
      #   ImageConfig
      # KmsKeyArn: String
      # Layers: 
      #   - String
      MemorySize: 128
      PackageType: Zip
      # ReservedConcurrentExecutions: Integer
      Role: !GetAtt LambdaExecutionRole.Arn
      Runtime: python3.9
      Tags:
        - Key: Environment
          Value: !Ref EnvironmentParam
        - Key: Description
          Value: This is the description of this specific resource.
        - Key: Documentation
          Value: !Ref DocumentationURLParam
        - Key: cit:contact-email
          Value: !Ref ContactEmailParam
        - Key: cit:version
          Value: !Ref VersionParam
        - Key: cit:source
          Value:  !Ref SourceURLParam
      Timeout: 10
      # TracingConfig: 
      #   TracingConfig
      # VpcConfig: 
      #   VpcConfig

  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Effect: "Allow"
            Principal:
              Service:
                - "lambda.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      Description: Role to allow Lambda execution for sns-teams-relay
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      RoleName: !Sub "sns-teams-relay-${EnvironmentParam}-lambda-execution-role"
      Tags:
        - Key: Environment
          Value: !Ref EnvironmentParam
        - Key: Description
          Value: This is the description of this specific resource.
        - Key: Documentation
          Value: !Ref DocumentationURLParam
        - Key: cit:contact-email
          Value: !Ref ContactEmailParam
        - Key: cit:version
          Value: !Ref VersionParam
        - Key: cit:source
          Value:  !Ref SourceURLParam

  AlarmSNSTopicNormalSubscription:
    Type: AWS::SNS::Subscription
    Condition: AlarmSNSTopicNormalCondition
    Properties:
      Protocol: lambda
      TopicArn: !Ref AlarmSNSTopicNormal
      Endpoint: !GetAtt SNStoTeamsRelay.Arn

  AlarmSNSTopicAlertSubscription:
    Type: AWS::SNS::Subscription
    Condition: AlarmSNSTopicAlertCondition
    Properties:
      Protocol: lambda
      TopicArn: !Ref AlarmSNSTopicAlert
      Endpoint: !GetAtt SNStoTeamsRelay.Arn

  GenericSNSTopicNormalSubscription:
    Type: AWS::SNS::Subscription
    Condition: GenericSNSTopicNormalCondition
    Properties:
      Protocol: lambda
      TopicArn: !Ref GenericSNSTopicNormal
      Endpoint: !GetAtt SNStoTeamsRelay.Arn

  GenericSNSTopicAlertSubscription:
    Type: AWS::SNS::Subscription
    Condition: GenericSNSTopicAlertCondition
    Properties:
      Protocol: lambda
      TopicArn: !Ref GenericSNSTopicAlert
      Endpoint: !GetAtt SNStoTeamsRelay.Arn

  AlarmSNSTopicNormalNormalPermission:
    Type: AWS::Lambda::Permission
    Condition: AlarmSNSTopicNormalCondition
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref SNStoTeamsRelay
      Principal: sns.amazonaws.com
      SourceAccount: !Ref AWS::AccountId
      SourceArn: !Ref AlarmSNSTopicNormal

  AlarmSNSTopicAlertPermission:
    Type: AWS::Lambda::Permission
    Condition: AlarmSNSTopicAlertCondition
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref SNStoTeamsRelay
      Principal: sns.amazonaws.com
      SourceAccount: !Ref AWS::AccountId
      SourceArn: !Ref AlarmSNSTopicAlert

  GenericSNSTopicNormalPermission:
    Type: AWS::Lambda::Permission
    Condition: GenericSNSTopicNormalCondition
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref SNStoTeamsRelay
      Principal: sns.amazonaws.com
      SourceAccount: !Ref AWS::AccountId
      SourceArn: !Ref GenericSNSTopicNormal

  GenericSNSTopicAlertPermission:
    Type: AWS::Lambda::Permission
    Condition: GenericSNSTopicAlertCondition
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref SNStoTeamsRelay
      Principal: sns.amazonaws.com
      SourceAccount: !Ref AWS::AccountId
      SourceArn: !Ref GenericSNSTopicAlert
